# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('elevation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('processed', models.BooleanField(default=False)),
                ('geo_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='core.GeoPosition')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_temperature', models.FloatField(blank=True, default=None, null=True)),
                ('average_wind_speed', models.FloatField(blank=True, default=None, null=True)),
                ('average_wind_direction', models.FloatField(blank=True, default=None, null=True)),
                ('records_count', models.IntegerField(default=0)),
                ('geo_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_summary', to='core.GeoPosition')),
            ],
        ),
    ]
